name: Secret

on:
  push:
    branches: [ main ]
    
jobs:
  secret:
    run-on: windows-latest
    steps:
      - name: Step 1
        run: |
          echo ${{secrets.NAME}}
          echo ${{secrets.NAME}} | sed 's/./& /g'
